import type { Metadata } from "next";
import { Poppins, Playfair_Display } from "next/font/google";
import "./globals.css";
import GlobalBottomBlur from "@/Ui/GlobalBottomBlur";
import FloatingNav from "@/Ui/FloatingNav";
import Footer from "@/layout/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  variable: "--font-poppins",
});

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
});
export const metadata: Metadata = {
  title: "WatNidea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased ${poppins.variable} ${playfair.variable}`}>
      <body className="min-h-full flex flex-col font-poppins">
        <FloatingNav />
        {children}
        <GlobalBottomBlur />
        <Footer />
      </body>
    </html>
  );
}
