import type { Metadata } from "next";
import "./globals.css";
import GlobalBottomBlur from "@/Ui/GlobalBottomBlur";
import FloatingNav from "@/Ui/FloatingNav";
import Footer from "@/layout/Footer";
export const metadata: Metadata = {
  title: "WatNidea",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`h-full antialiased`}>
      <body className="min-h-full flex flex-col">
        <FloatingNav />
        {children}
        <GlobalBottomBlur />
        <Footer />
      </body>
    </html>
  );
}
